apiVersion: batch/v1
kind: CronJob
metadata:
  name: caller-app
  namespace: ipaas
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: caller-app
            image: luangazin/caller-app:0.0.1
            imagePullPolicy: IfNotPresent
            args:
            # - /bin/sh
            # - -c
            # - date; echo Hello from the Kubernetes cluster
            - /bin/sh
            - -c
            - "curl -d '{\"logbody\": \"dasds\"}' -H 'Content-Type:application/json' -X POST http://ipaas-log-app-service:8080/log"
          restartPolicy: OnFailure