apiVersion: v1
kind: Service
metadata:
  name: ipaas-log-app-service
  namespace: ipaas
  labels:
    run: ipaas-log-app-service
spec:
  selector:
    run: ipaas-log-app
  ports:
  - port: 8080
    protocol: TCP